### ISSUE TITLE
git not found on fresh image

### ISSUE THREAD

**Issue by altmattr** [mqjasper/mq-pi-gen#3]
by the way, I've been testing it and it is really nice :)

**Comment by altmattr** [comment]
I'm not seeing tflite either, so predictions can't run.

**Comment by mqjasper** [comment]
Have now got tflite and opencv installing as part of the build process, which should sort that out. Not sure what the issue is with git, as the latest image build I have been running seems to have git installed. I have added it to the packages list anyway, hopefully that should resolve any weird popups
